import os
import time

def load(times):
  os.system("clear")
  for i in range(0, times):
    print("Loading... ")
    time.sleep(0.1)
    os.system("clear")
    print("Loading...  ")
    time.sleep(0.1)
    os.system("clear")
    print("Loading...  ")
    time.sleep(0.1)
    os.system("clear")
    print("Loading...  ")
    time.sleep(0.1)
    os.system("clear")
    print("Loading...  ")
    time.sleep(0.1)
    os.system("clear")
    print("Loading...  ")
    time.sleep(0.1)
    os.system("clear")
    print("Loading...  ")
    time.sleep(0.1)
    os.system("clear")
    print("Loading...  ")
    time.sleep(0.1)
    os.system("clear")
    print("Loading...  ")
    time.sleep(0.1)
    os.system("clear")
    print("Loading...  ")
    time.sleep(0.1)
    os.system("clear")
    print("Loading...  ")
    time.sleep(0.1)
    os.system("clear")
    print("Loading...  ")
    time.sleep(0.1)
    os.system("clear")
    print("Loading...  ")
    time.sleep(0.1)
    os.system("clear")
    print("Loading...  ")
    time.sleep(0.1)
    os.system("clear")
    print("Loading...  ")
    time.sleep(0.1)
    os.system("clear")
    print("Loading...  ")
    time.sleep(0.1)
    os.system("clear")
    print("Loading...  ")
    time.sleep(0.1)
    os.system("clear")
    print("Loading...  ")
    time.sleep(0.1)
    os.system("clear")
    print("Loading...  ")
    time.sleep(0.1)
    os.system("clear")
    print("Loading...  ")
    time.sleep(0.1)
    os.system("clear")
    print("Loading...  ")
    time.sleep(0.1)
    os.system("clear")
    print("Loading...  ")
    time.sleep(0.1)
    os.system("clear")
    print("Loading...  ")
    time.sleep(0.1)
    os.system("clear")
    print("Loading...  ")
    time.sleep(0.1)
    os.system("clear")
    print("Loading...  ")
    time.sleep(0.1)
    os.system("clear")
    print("Loading...  ")
    time.sleep(0.1)
    os.system("clear")
    print("Loading...  ")
    time.sleep(0.1)
    os.system("clear")
    print("Loading...  ")
    time.sleep(0.1)
    os.system("clear")
    print("Loading...  ")
    time.sleep(0.1)
    os.system("clear")
    print("Loading...  ")
    time.sleep(0.1)
    os.system("clear")
    print("Loading...  ")
    time.sleep(0.1)
  os.system("clear")
  os.system('echo "Done!"')

load(1)

from alive_progress import alive_bar

with alive_bar(100, theme="smooth") as bar:
    for i in range(100):
        time.sleep(0.01)
        bar()